/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Util.Utilidades;
import java.awt.Frame;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javafx.scene.input.KeyCode;
import javax.swing.JTextField;

/**
 *
 * @author juana
 */
public class Loguin_interfaz extends javax.swing.JFrame {

    String nombreUsuario;
    Socket conexionSocket;
    BufferedReader inputSocket;
    PrintWriter outputSocket;
    
    public Loguin_interfaz() {
        
        initComponents();
        requestFocusInWindow();
        
        iniciarConexion();
        setTitle("AyG Staff");
        
        //setIconImage(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        dni_tf = new javax.swing.JTextField();
        clave_tf = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        acceder_bt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        error_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(74, 31, 61));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logoAppEscritorioAyG.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(186, 79, 84));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(186, 79, 84));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("P E R S O N A L");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(39, 39, 39))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(186, 79, 84));

        dni_tf.setBackground(new java.awt.Color(186, 79, 84));
        dni_tf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dni_tf.setForeground(new java.awt.Color(255, 255, 255));
        dni_tf.setText("DNI");
        dni_tf.setToolTipText("DNI"); // NOI18N
        dni_tf.setBorder(null);
        dni_tf.setCaretColor(new java.awt.Color(255, 255, 255));
        dni_tf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dni_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLostDNI(evt);
            }
        });
        dni_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dni_tfMouseClicked(evt);
            }
        });
        dni_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dni_tfActionPerformed(evt);
            }
        });
        dni_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPresedDNI(evt);
            }
        });

        clave_tf.setBackground(new java.awt.Color(186, 79, 84));
        clave_tf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        clave_tf.setForeground(new java.awt.Color(255, 255, 255));
        clave_tf.setText("-----");
        clave_tf.setToolTipText("Clave de trabajador");
        clave_tf.setBorder(null);
        clave_tf.setCaretColor(new java.awt.Color(255, 255, 255));
        clave_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FocusGainedPass(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FocusLostPass(evt);
            }
        });
        clave_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clave_tfKeyPressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_identification_documents_30px_1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_key_2_30px.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(186, 79, 84));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        acceder_bt.setForeground(new java.awt.Color(255, 255, 255));
        acceder_bt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceder_bt.setText("Acceder");
        acceder_bt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceder_btMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(acceder_bt, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(acceder_bt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_multiply_30px.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        error_lb.setForeground(new java.awt.Color(255, 255, 255));
        error_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                error_lbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(dni_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(clave_tf)
                    .addComponent(jSeparator1))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(error_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dni_tf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clave_tf))
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(error_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        dni_tf.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dni_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dni_tfActionPerformed
        
    }//GEN-LAST:event_dni_tfActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void focusLostDNI(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLostDNI
        JTextField DNITextField=(JTextField)evt.getSource();
        if(DNITextField.getText().equalsIgnoreCase("")){
            DNITextField.setText("DNI");
        }
    }//GEN-LAST:event_focusLostDNI

    private void dni_tfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dni_tfMouseClicked
        JTextField DNITextField=(JTextField)evt.getSource();
        if(DNITextField.getText().equalsIgnoreCase("DNI")){
            DNITextField.setText("");
        }
        
    }//GEN-LAST:event_dni_tfMouseClicked

    private void keyPresedDNI(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPresedDNI
        
        if(dni_tf.getText().equalsIgnoreCase("DNI")){
            dni_tf.setText("");
            
        }
        
        char teclaPulsada=evt.getKeyChar();
        
        if(((int)teclaPulsada)==10) log();
        
        
    }//GEN-LAST:event_keyPresedDNI

    private void FocusGainedPass(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FocusGainedPass
        if(clave_tf.getText().equalsIgnoreCase("-----")){
            clave_tf.setText("");
        }
            
    }//GEN-LAST:event_FocusGainedPass

    private void FocusLostPass(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FocusLostPass
         if(clave_tf.getText().equalsIgnoreCase("")){
            clave_tf.setText("-----");
        }
    }//GEN-LAST:event_FocusLostPass

    private void acceder_btMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceder_btMouseClicked
        log();


    }//GEN-LAST:event_acceder_btMouseClicked

    private void error_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error_lbMouseClicked
        error_lb.setText("");
        iniciarConexion();
    }//GEN-LAST:event_error_lbMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        char teclaPulsada=evt.getKeyChar();
        System.out.println(teclaPulsada);
    }//GEN-LAST:event_formKeyPressed

    private void clave_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clave_tfKeyPressed
        char teclaPulsada=evt.getKeyChar();
        if(((int)teclaPulsada)==10) log();
    }//GEN-LAST:event_clave_tfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        final JTextField textFieldB = new JTextField("hola");
//        
//        add(textFieldB);
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loguin_interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acceder_bt;
    private javax.swing.JPasswordField clave_tf;
    private javax.swing.JTextField dni_tf;
    private javax.swing.JLabel error_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    
    
    public void log(){
        String dni = dni_tf.getText();
        String clave = clave_tf.getText();

        int resultadoLog = logIn(dni, clave);

        switch (resultadoLog) {
            case -1:
                error_lb.setText("Credenciales incorrectas. Intentalo de nuevo");
                break;
            case 1:
                System.out.println("Log admin:"+nombreUsuario);
                new Menu_admin_interfaz(inputSocket,outputSocket, this.nombreUsuario).setVisible(true);
                this.dispose();
                break;
            case 2:
                System.out.println("Log entrenador");
                new Menu_coach_interfaz(inputSocket,outputSocket, nombreUsuario).setVisible(true);
                this.dispose();
                
                break;
        }
    }
    private int logIn(String dni, String clave) {
        int resultado=-1;
        try {
            outputSocket.println("C4-LOG_TRABAJADOR:" + dni + "," + clave);
            outputSocket.flush();
            String mensajeEntrada = inputSocket.readLine();
            
            if(mensajeEntrada.contains("S2-LOG_INCORRECTO")){
                resultado=-1;
            }else if(mensajeEntrada.contains("S10-LOG_CORRECTO_TR")){
                String rol=Utilidades.obtenerParametro(mensajeEntrada, 1);
                String nombre=Utilidades.obtenerParametro(mensajeEntrada, 2);
                String apellidos=Utilidades.obtenerParametro(mensajeEntrada, 3);
                this.nombreUsuario=nombre+" "+apellidos;
                resultado=Integer.parseInt(rol);
                
                
            }
            
            
            
        } catch (IOException ioe) {
            
        }

        return resultado;
    }
    
    
    

    private void iniciarConexion() {
        try {
            //Replace below IP with the IP of that device in which server socket open.
            //If you change port then change the port number in the server side code also.
            conexionSocket = new Socket("192.168.0.11", 9002);
            outputSocket = new PrintWriter(conexionSocket.getOutputStream());
            inputSocket = new BufferedReader(new InputStreamReader(conexionSocket.getInputStream()));
            

            
        } catch (IOException e) {
            e.printStackTrace();
            error_lb.setText("Error de conexion con servidor ¿Volver a intentar?");
        }
    }
    
    
}
