/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Paneles_Admin.CambiaPanel;
import Paneles_Admin.pnl_Claves;
import Paneles_Admin.pnl_Clientes;
import Paneles_Admin.pnl_Home_Adm;
import Paneles_Admin.pnl_Trabajadores;
import Paneles_coach.pnl_AltaTabla;
import Paneles_coach.pnl_Clases;
import Paneles_coach.pnl_Horario;
import Util.Utilidades;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author juana
 */
public class Menu_admin_interfaz extends javax.swing.JFrame {

    
    
    BufferedReader inSocket;
    PrintWriter outSocket;
    
    String nombreUsuario;
    Color colorFondo;
    
    
    
    public Menu_admin_interfaz() {
    
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Menu Administrador");
        colorFondo = new Color(186, 79, 84);

    }
    
     public Menu_admin_interfaz(BufferedReader inSocket, PrintWriter outSocket, String nombreUsuario) {
         this.nombreUsuario = nombreUsuario;
         setTitle("Administrador-"+nombreUsuario);
         this.inSocket=inSocket;
         this.outSocket=outSocket;
         colorFondo = new Color(186, 79, 84);

         initComponents();

         this.nombreUsuario_lb.setText(nombreUsuario);

         setLocationRelativeTo(this);
         new CambiaPanel(this.contenido_panel, new pnl_Home_Adm(this,inSocket,outSocket));
         //esconderMenu();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        barra_panel = new javax.swing.JPanel();
        rSButtonMetro1 = new Recursos.RSButtonMetro();
        tema_bt = new Recursos.RSButtonMetro();
        home_bt = new Recursos.RSButtonMetro();
        menu_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreUsuario_lb = new javax.swing.JLabel();
        clientes_bt = new Recursos.RSButtonMetro();
        trabajadores_bt = new Recursos.RSButtonMetro();
        clavesAcceso_bt = new Recursos.RSButtonMetro();
        cerrarSession_bt = new Recursos.RSButtonMetro();
        clases_bt1 = new Recursos.RSButtonMetro();
        clases_bt = new Recursos.RSButtonMetro();
        clases_bt2 = new Recursos.RSButtonMetro();
        contenido_panel = new javax.swing.JPanel();
        contenidofake_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(186, 79, 84));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(186, 79, 84));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra_panel.setBackground(new java.awt.Color(74, 31, 61));
        barra_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMetro1.setBackground(new java.awt.Color(74, 31, 61));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_multiply_40px.png"))); // NOI18N
        rSButtonMetro1.setColorHover(new java.awt.Color(112, 62, 97));
        rSButtonMetro1.setColorNormal(new java.awt.Color(74, 31, 61));
        rSButtonMetro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickedCerrar(evt);
            }
        });
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        barra_panel.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 0, 60, 50));

        tema_bt.setBackground(new java.awt.Color(74, 31, 61));
        tema_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_paint_palette_40px_2.png"))); // NOI18N
        tema_bt.setColorHover(new java.awt.Color(112, 62, 97));
        tema_bt.setColorNormal(new java.awt.Color(74, 31, 61));
        tema_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarTema(evt);
            }
        });
        barra_panel.add(tema_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 50));

        home_bt.setBackground(new java.awt.Color(74, 31, 61));
        home_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_home_40px_1.png"))); // NOI18N
        home_bt.setColorHover(new java.awt.Color(112, 62, 97));
        home_bt.setColorNormal(new java.awt.Color(74, 31, 61));
        home_bt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_btMouseClicked(evt);
            }
        });
        home_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btActionPerformed(evt);
            }
        });
        barra_panel.add(home_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jPanel1.add(barra_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 50));

        menu_panel.setBackground(new java.awt.Color(74, 31, 61));
        menu_panel.setForeground(new java.awt.Color(186, 79, 84));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_imac_125px_1.png"))); // NOI18N

        nombreUsuario_lb.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        nombreUsuario_lb.setForeground(new java.awt.Color(204, 204, 204));
        nombreUsuario_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUsuario_lb.setText("Miguel Angel Bolivar");
        nombreUsuario_lb.setToolTipText("");

        clientes_bt.setBackground(new java.awt.Color(74, 31, 61));
        clientes_bt.setForeground(new java.awt.Color(204, 204, 204));
        clientes_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_human_head_40px_2.png"))); // NOI18N
        clientes_bt.setText("CLIENTES");
        clientes_bt.setColorHover(new java.awt.Color(112, 62, 97));
        clientes_bt.setColorNormal(new java.awt.Color(74, 31, 61));
        clientes_bt.setColorTextHover(new java.awt.Color(204, 204, 204));
        clientes_bt.setColorTextNormal(new java.awt.Color(204, 204, 204));
        clientes_bt.setColorTextPressed(new java.awt.Color(204, 204, 204));
        clientes_bt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clientes_bt.setHideActionText(true);
        clientes_bt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clientes_bt.setIconTextGap(10);
        clientes_bt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientes_btMouseClicked(evt);
            }
        });
        clientes_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientes_btActionPerformed(evt);
            }
        });

        trabajadores_bt.setBackground(new java.awt.Color(74, 31, 61));
        trabajadores_bt.setForeground(new java.awt.Color(204, 204, 204));
        trabajadores_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_personal_trainer_40px_5.png"))); // NOI18N
        trabajadores_bt.setText("TRABAJADORES");
        trabajadores_bt.setColorHover(new java.awt.Color(112, 62, 97));
        trabajadores_bt.setColorNormal(new java.awt.Color(74, 31, 61));
        trabajadores_bt.setColorTextHover(new java.awt.Color(204, 204, 204));
        trabajadores_bt.setColorTextNormal(new java.awt.Color(204, 204, 204));
        trabajadores_bt.setColorTextPressed(new java.awt.Color(204, 204, 204));
        trabajadores_bt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        trabajadores_bt.setHideActionText(true);
        trabajadores_bt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        trabajadores_bt.setIconTextGap(10);
        trabajadores_bt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trabajadores_btMouseClicked(evt);
            }
        });

        clavesAcceso_bt.setBackground(new java.awt.Color(74, 31, 61));
        clavesAcceso_bt.setForeground(new java.awt.Color(204, 204, 204));
        clavesAcceso_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_key_40px_2.png"))); // NOI18N
        clavesAcceso_bt.setText("CLAVES ACCESO");
        clavesAcceso_bt.setColorHover(new java.awt.Color(112, 62, 97));
        clavesAcceso_bt.setColorNormal(new java.awt.Color(74, 31, 61));
        clavesAcceso_bt.setColorTextHover(new java.awt.Color(204, 204, 204));
        clavesAcceso_bt.setColorTextNormal(new java.awt.Color(204, 204, 204));
        clavesAcceso_bt.setColorTextPressed(new java.awt.Color(204, 204, 204));
        clavesAcceso_bt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clavesAcceso_bt.setHideActionText(true);
        clavesAcceso_bt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clavesAcceso_bt.setIconTextGap(12);
        clavesAcceso_bt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clavesAcceso_btMouseClicked(evt);
            }
        });
        clavesAcceso_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavesAcceso_btActionPerformed(evt);
            }
        });

        cerrarSession_bt.setBackground(new java.awt.Color(74, 31, 61));
        cerrarSession_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_exit_40px_1.png"))); // NOI18N
        cerrarSession_bt.setText("CERRAR SESION");
        cerrarSession_bt.setColorHover(new java.awt.Color(112, 62, 97));
        cerrarSession_bt.setColorNormal(new java.awt.Color(74, 31, 61));
        cerrarSession_bt.setColorTextHover(new java.awt.Color(204, 204, 204));
        cerrarSession_bt.setColorTextNormal(new java.awt.Color(204, 204, 204));
        cerrarSession_bt.setColorTextPressed(new java.awt.Color(204, 204, 204));
        cerrarSession_bt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cerrarSession_bt.setHideActionText(true);
        cerrarSession_bt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cerrarSession_bt.setIconTextGap(10);
        cerrarSession_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSession_btActionPerformed(evt);
            }
        });

        clases_bt1.setBackground(new java.awt.Color(74, 31, 61));
        clases_bt1.setForeground(new java.awt.Color(204, 204, 204));
        clases_bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_calendar_40px.png"))); // NOI18N
        clases_bt1.setText("HORARIOS");
        clases_bt1.setColorHover(new java.awt.Color(112, 62, 97));
        clases_bt1.setColorNormal(new java.awt.Color(74, 31, 61));
        clases_bt1.setColorTextHover(new java.awt.Color(204, 204, 204));
        clases_bt1.setColorTextNormal(new java.awt.Color(204, 204, 204));
        clases_bt1.setColorTextPressed(new java.awt.Color(204, 204, 204));
        clases_bt1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clases_bt1.setHideActionText(true);
        clases_bt1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clases_bt1.setIconTextGap(12);
        clases_bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clases_bt1ActionPerformed(evt);
            }
        });

        clases_bt.setBackground(new java.awt.Color(74, 31, 61));
        clases_bt.setForeground(new java.awt.Color(204, 204, 204));
        clases_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_dancing_40px_1.png"))); // NOI18N
        clases_bt.setText("CLASES");
        clases_bt.setColorHover(new java.awt.Color(112, 62, 97));
        clases_bt.setColorNormal(new java.awt.Color(74, 31, 61));
        clases_bt.setColorTextHover(new java.awt.Color(204, 204, 204));
        clases_bt.setColorTextNormal(new java.awt.Color(204, 204, 204));
        clases_bt.setColorTextPressed(new java.awt.Color(204, 204, 204));
        clases_bt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clases_bt.setHideActionText(true);
        clases_bt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clases_bt.setIconTextGap(12);
        clases_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clases_btActionPerformed(evt);
            }
        });

        clases_bt2.setBackground(new java.awt.Color(74, 31, 61));
        clases_bt2.setForeground(new java.awt.Color(204, 204, 204));
        clases_bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_reset_40px.png"))); // NOI18N
        clases_bt2.setText("RESET. RESERVAS");
        clases_bt2.setColorHover(new java.awt.Color(112, 62, 97));
        clases_bt2.setColorNormal(new java.awt.Color(74, 31, 61));
        clases_bt2.setColorTextHover(new java.awt.Color(204, 204, 204));
        clases_bt2.setColorTextNormal(new java.awt.Color(204, 204, 204));
        clases_bt2.setColorTextPressed(new java.awt.Color(204, 204, 204));
        clases_bt2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clases_bt2.setHideActionText(true);
        clases_bt2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clases_bt2.setIconTextGap(12);
        clases_bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clases_bt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu_panelLayout = new javax.swing.GroupLayout(menu_panel);
        menu_panel.setLayout(menu_panelLayout);
        menu_panelLayout.setHorizontalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarSession_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clientes_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(trabajadores_bt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nombreUsuario_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clavesAcceso_bt, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addComponent(clases_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clases_bt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clases_bt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menu_panelLayout.setVerticalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreUsuario_lb)
                .addGap(52, 52, 52)
                .addComponent(trabajadores_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clientes_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clavesAcceso_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clases_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clases_bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clases_bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(cerrarSession_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(menu_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, 850));

        contenido_panel.setBackground(new java.awt.Color(255, 255, 255));
        contenido_panel.setForeground(new java.awt.Color(255, 255, 255));
        contenido_panel.setOpaque(false);
        contenido_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contenido_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contenido_panelMouseEntered(evt);
            }
        });
        contenido_panel.setLayout(new javax.swing.BoxLayout(contenido_panel, javax.swing.BoxLayout.LINE_AXIS));

        contenidofake_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        contenidofake_lbl.setForeground(new java.awt.Color(255, 255, 255));
        contenidofake_lbl.setText("HOME");
        contenido_panel.add(contenidofake_lbl);

        jPanel1.add(contenido_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 1370, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void mouseClickedCerrar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickedCerrar
        System.exit(0);
    }//GEN-LAST:event_mouseClickedCerrar

    private void cerrarSession_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSession_btActionPerformed
        try {
            new Loguin_interfaz().setVisible(true);
            this.dispose();
        } catch (Exception e) {
            System.out.println("Fallo deslogueando");
        }
    }//GEN-LAST:event_cerrarSession_btActionPerformed

    private void cambiarTema(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarTema
        
        colorFondo=this.jPanel1.getBackground();
        if(colorFondo.equals(new Color(186,79,84))){
            colorFondo=new Color(59, 52, 52);
            this.jPanel1.setBackground(colorFondo);
        }else{
            colorFondo=new Color(186,79,84);
            this.jPanel1.setBackground(colorFondo);
        }
    }//GEN-LAST:event_cambiarTema

    private void contenido_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contenido_panelMouseClicked
        //esconderMenu();
        
    }//GEN-LAST:event_contenido_panelMouseClicked

    private void home_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btActionPerformed
        //esconderMenu();
        
    }//GEN-LAST:event_home_btActionPerformed

    private void contenido_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contenido_panelMouseEntered
        //esconderMenu();
    }//GEN-LAST:event_contenido_panelMouseEntered

    private void clientes_btMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientes_btMouseClicked
        new CambiaPanel(this.contenido_panel, new pnl_Clientes(this,inSocket,outSocket));
    }//GEN-LAST:event_clientes_btMouseClicked

    private void home_btMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btMouseClicked
        new CambiaPanel(this.contenido_panel, new pnl_Home_Adm(this,inSocket,outSocket));
    }//GEN-LAST:event_home_btMouseClicked

    private void trabajadores_btMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trabajadores_btMouseClicked
       new CambiaPanel(this.contenido_panel, new pnl_Trabajadores(this,inSocket,outSocket));
    }//GEN-LAST:event_trabajadores_btMouseClicked

    private void clavesAcceso_btMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clavesAcceso_btMouseClicked
        new CambiaPanel(this.contenido_panel, new pnl_Claves(this,inSocket,outSocket));
    }//GEN-LAST:event_clavesAcceso_btMouseClicked

    private void clientes_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientes_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientes_btActionPerformed

    private void clavesAcceso_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clavesAcceso_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clavesAcceso_btActionPerformed

    private void clases_bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clases_bt1ActionPerformed
        cambiarPanelContenido( new pnl_Horario(this,inSocket,outSocket));
    }//GEN-LAST:event_clases_bt1ActionPerformed

    private void clases_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clases_btActionPerformed

        cambiarPanelContenido( new pnl_Clases(this,inSocket,outSocket));
    }//GEN-LAST:event_clases_btActionPerformed

    private void clases_bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clases_bt2ActionPerformed
        int respuesta=JOptionPane.showConfirmDialog(null, "¿Quiere eliminar todas las reservas hechas hasta el momento?","Confirmar",0);
        if(respuesta==0){
            resetearReservas();
        }
    }//GEN-LAST:event_clases_bt2ActionPerformed
   
    
    
    
    /* ACCIONES DE MENU DEPLEGABLE (desactivado)
    
    private void quitarMenu(){
        menu_panel.setVisible(false);
    }
    private void mostrarMenu(){
        menu_panel.setVisible(true);
    }
    private void esconderMenu() {
        
        int posicion = this.menu_panel.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -260, 2, 2, menu_panel);
        }
        menu_panel.setVisible(false);
        
    }
    private void desplegarMenu(){
        
        menu_panel.setVisible(true);
        int posicion = this.menu_panel.getX();
        if(posicion <= -1){
            Animacion.Animacion.mover_derecha(-260, 0, 2, 2, menu_panel);
        }
        int posicionContenido = this.contenido_panel.getX();
        if(posicionContenido<10){
            Animacion.Animacion.mover_derecha(0, 260, 2, 2, contenido_panel);
            contenido_panel.setLocation(260, 0);
            this.repaint();
        }
        
    }
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_admin_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_admin_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_admin_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_admin_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_admin_interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra_panel;
    private javax.swing.ButtonGroup buttonGroup1;
    private Recursos.RSButtonMetro cerrarSession_bt;
    private Recursos.RSButtonMetro clases_bt;
    private Recursos.RSButtonMetro clases_bt1;
    private Recursos.RSButtonMetro clases_bt2;
    private Recursos.RSButtonMetro clavesAcceso_bt;
    private Recursos.RSButtonMetro clientes_bt;
    private javax.swing.JPanel contenido_panel;
    private javax.swing.JLabel contenidofake_lbl;
    private Recursos.RSButtonMetro home_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JLabel nombreUsuario_lb;
    private Recursos.RSButtonMetro rSButtonMetro1;
    private Recursos.RSButtonMetro tema_bt;
    private Recursos.RSButtonMetro trabajadores_bt;
    // End of variables declaration//GEN-END:variables

//    private void iniciarConexion() {
//        try {
//            outSocket = new PrintWriter(socketServidor.getOutputStream());
//            inSocket = new BufferedReader(new InputStreamReader(socketServidor.getInputStream()));
//
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//    }
    
    
    public void cambiarPanelContenido(JPanel panelNuevo){
        new CambiaPanel(this.contenido_panel, panelNuevo);
    }

    public void resetearReservas() {
        
       
        
        Thread thread_eliminarReservas = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    outSocket.write("C46-RESETEAR_RESERVAS\n");
                    outSocket.flush();

                    String respuestaServidor = inSocket.readLine();
                    if (respuestaServidor.contains("S68-RESETEADAS")) {
                        JOptionPane.showMessageDialog(null, "Todas las reservas han sido eliminadas");
                    } else {
                        System.out.println("Respuesta erronea del server:" + respuestaServidor);
                        JOptionPane.showMessageDialog(null, "Error servidor.");
                    }

                } catch (IOException ex) {
                    Logger.getLogger(pnl_AltaTabla.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        thread_eliminarReservas.setDaemon(true);
        thread_eliminarReservas.start();
    }

    
}
