/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Paneles_Admin.pnl_AltaCliente;
import Paneles_coach.pnl_AltaClase;
import Paneles_coach.pnl_AltaEjercicio;
import Util.Utilidades;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.MimetypesFileTypeMap;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author juana
 */
public class Subir_Foto_interfaz extends javax.swing.JFrame {

    pnl_AltaCliente panelPadreCliente;
    pnl_AltaClase panelPadreClase;
    pnl_AltaEjercicio panelPadreEjercicio;

    int nEjercicio;

    public Subir_Foto_interfaz() {
        initComponents();
    }

    public Subir_Foto_interfaz(pnl_AltaCliente panelPadre) {
        initComponents();
        this.panelPadreCliente = panelPadre;
        nEjercicio = 1;
    }

    public Subir_Foto_interfaz(pnl_AltaClase panelPadre) {
        initComponents();
        this.panelPadreClase = panelPadre;
        nEjercicio = 2;
    }

    public Subir_Foto_interfaz(pnl_AltaEjercicio panelPadre) {
        initComponents();
        this.panelPadreEjercicio = panelPadre;
        nEjercicio = 3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruta_tf = new javax.swing.JTextField();
        selectorRuta_bt = new javax.swing.JButton();
        subir_bt = new javax.swing.JButton();
        error_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ruta_tf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        selectorRuta_bt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        selectorRuta_bt.setText("...");
        selectorRuta_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorRuta_btActionPerformed(evt);
            }
        });

        subir_bt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        subir_bt.setText("SUBIR IMAGEN");
        subir_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subir_btActionPerformed(evt);
            }
        });

        error_lb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        error_lb.setForeground(new java.awt.Color(204, 0, 51));
        error_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(subir_bt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(error_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ruta_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(selectorRuta_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruta_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorRuta_bt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(subir_bt)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectorRuta_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorRuta_btActionPerformed
        //Crear objeto selector de archivos
        JFileChooser fileChooser = new JFileChooser();

        //Añadirle un filtro para que solo muestre el tipo de archivos que nos interesa, en este caso de fotos png y jpg
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("imagenes", "png", "jpg");
        fileChooser.setFileFilter(filtro);

        //Mostrar la ventana del seleccionador y recoger la opcion seleccionada (si ha "aceptado", "cancelado"...)
        int seleccion = fileChooser.showOpenDialog(this);

        //Si finalmente la opcion seleccionada es "aceptar" pues recogerá el File que se ha seleecionado, obtendra su ruta y la cambiará en el EditText de esta.
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File foto = fileChooser.getSelectedFile();
            ruta_tf.setText(foto.getAbsolutePath());
        }
    }//GEN-LAST:event_selectorRuta_btActionPerformed

    private void subir_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subir_btActionPerformed
        //Comprobará la ruta del TextField (Que habra sido introducida manualmente o con el FileChooser) y la subirá al servidor
        File foto = new File(ruta_tf.getText());
        //Comprobar si el archivo existe
        if (foto.exists()) {
            //Comprobar si es una foto
            String mimetype = new MimetypesFileTypeMap().getContentType(foto);
            String type = mimetype.split("/")[0];
            if (type.equals("image")) {
                subirFotoServidor(foto);
            } else {
                error_lb.setText("El archivo indicado no es una imagen (png o jpg)");
            }

        } else {
            error_lb.setText("El archivo indicado no existe. Vuelva a indicar la ruta.");
        }
    }//GEN-LAST:event_subir_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subir_Foto_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subir_Foto_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subir_Foto_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subir_Foto_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subir_Foto_interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error_lb;
    private javax.swing.JTextField ruta_tf;
    private javax.swing.JButton selectorRuta_bt;
    private javax.swing.JButton subir_bt;
    // End of variables declaration//GEN-END:variables

    private void subirFotoServidor(File foto) {
        
        try {

            //1 Convierto la foto a bytes[]
            byte[] imagenEnBytes = Files.readAllBytes(foto.toPath());

            //2 Crea una peticion Socket para enviar la imagen y sus flujos
            final String DIRECCION_IP = "192.168.0.11";
            final int PUERTO_ENVIAR = 9004;
            Socket conexionSocketEnviarImagen = new Socket(DIRECCION_IP, PUERTO_ENVIAR);
            BufferedOutputStream outputSocket = new BufferedOutputStream(conexionSocketEnviarImagen.getOutputStream());
            BufferedReader inputSocket = new BufferedReader(new InputStreamReader(conexionSocketEnviarImagen.getInputStream()));

            //3 Envia la imagen
            outputSocket.write(imagenEnBytes, 0, imagenEnBytes.length);
            outputSocket.flush();
            //4 Recibir la ruta de la imagen o el error
            String theInput;
            theInput = inputSocket.readLine();
            
            if (theInput.contains("S22-IMAGEN_SUBIDA")) {
                String rutaImagenSubida = Utilidades.obtenerParametro(theInput, 1);
                añadirRutaImagenSubidaEnPanel(rutaImagenSubida);
                this.dispose();
            } else {
                error_lb.setText("Error del servidor, intentelo mas tarde.");
            }
            outputSocket.close();
            inputSocket.close();
            conexionSocketEnviarImagen.close();

        } catch (IOException ex) {
            Logger.getLogger(Subir_Foto_interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void añadirRutaImagenSubidaEnPanel(String rutaImagenSubida) {

        switch (nEjercicio) {
            case 1:
                panelPadreCliente.añadirRutaImagenSubida(rutaImagenSubida);
                break;
            case 2:
                panelPadreClase.añadirRutaImagenSubida(rutaImagenSubida);
                break;
            case 3:
                panelPadreEjercicio.añadirRutaImagenSubida(rutaImagenSubida);
                break;
        }
    }
}

