/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles_coach;

import Paneles_Admin.*;
import Interfaces.Menu_admin_interfaz;
import Interfaces.Menu_coach_interfaz;
import Util.Utilidades;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.nio.file.Files;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import static javax.swing.BorderFactory.createEmptyBorder;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juana
 */
public class pnl_Rutinas extends javax.swing.JPanel {

    Menu_coach_interfaz interfaz_menu_padre;
    BufferedReader inSocket;
    PrintWriter outSocket;

    DefaultTableModel defaultTableMode;

    int filtradoRolAnterior;
    
    String dniSeleccionado=null;
    String rutaFotoSeleccionada=null;

    public pnl_Rutinas(Menu_coach_interfaz interfaz_menu_padre, BufferedReader inSocket, PrintWriter outSocket) {
        initComponents();
        filtradoRolAnterior = 0;
        this.interfaz_menu_padre = interfaz_menu_padre;

        this.inSocket = inSocket;
        this.outSocket = outSocket;
        System.out.println(outSocket);

        darFormatoTabla();

        cargarTablaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_lb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        eliminar_lb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        patronBuscar_tf = new javax.swing.JTextField();
        peso_lbl = new javax.swing.JLabel();
        notas_lbl = new javax.swing.JLabel();
        altura_lbl = new javax.swing.JLabel();
        eliminar_lb1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        titulo_lb2 = new javax.swing.JLabel();
        titulo_lb3 = new javax.swing.JLabel();
        subirImg_bt = new javax.swing.JButton();
        agregarEjercicio_bt1 = new javax.swing.JButton();
        eliminarEjercicio_bt2 = new javax.swing.JButton();
        eliminar_lb2 = new javax.swing.JLabel();
        eliminar_lb3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1390, 850));

        titulo_lb.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        titulo_lb.setForeground(new java.awt.Color(255, 255, 255));
        titulo_lb.setText("RUTINAS");

        jScrollPane1.setBackground(new java.awt.Color(74, 31, 61));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(74, 31, 61));
        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(222, 222, 222));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre", "Apellido", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(38);
        jTable1.setSelectionBackground(new java.awt.Color(101, 58, 88));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(3).setMinWidth(0);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Correo");
        }

        eliminar_lb.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        eliminar_lb.setForeground(new java.awt.Color(255, 255, 255));
        eliminar_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_remove_25px.png"))); // NOI18N
        eliminar_lb.setText("Eliminar");
        eliminar_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar_lbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminar_lbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminar_lbMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(74, 31, 61));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_search_30px_1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        patronBuscar_tf.setBackground(new java.awt.Color(74, 31, 61));
        patronBuscar_tf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        patronBuscar_tf.setForeground(new java.awt.Color(255, 255, 255));
        patronBuscar_tf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        patronBuscar_tf.setToolTipText("");
        patronBuscar_tf.setBorder(null);
        patronBuscar_tf.setCaretColor(new java.awt.Color(255, 255, 255));
        patronBuscar_tf.setOpaque(false);
        patronBuscar_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                patronBuscar_tfKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(patronBuscar_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(patronBuscar_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        peso_lbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        peso_lbl.setForeground(new java.awt.Color(255, 255, 255));
        peso_lbl.setText(" ");

        notas_lbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        notas_lbl.setForeground(new java.awt.Color(255, 255, 255));
        notas_lbl.setText(" ");
        notas_lbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        altura_lbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        altura_lbl.setForeground(new java.awt.Color(255, 255, 255));
        altura_lbl.setText(" ");

        eliminar_lb1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        eliminar_lb1.setForeground(new java.awt.Color(255, 255, 255));
        eliminar_lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_plus_30px.png"))); // NOI18N
        eliminar_lb1.setText("Nueva rutina personalizada");
        eliminar_lb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar_lb1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminar_lb1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminar_lb1MouseExited(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(74, 31, 61));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(74, 31, 61));
        jScrollPane2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(222, 222, 222));
        jTable2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Dias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setOpaque(false);
        jTable2.setRowHeight(38);
        jTable2.setSelectionBackground(new java.awt.Color(101, 58, 88));
        jTable2.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        titulo_lb2.setFont(new java.awt.Font("Corbel Light", 1, 30)); // NOI18N
        titulo_lb2.setForeground(new java.awt.Color(255, 255, 255));
        titulo_lb2.setText("Tablas");

        titulo_lb3.setFont(new java.awt.Font("Corbel Light", 1, 30)); // NOI18N
        titulo_lb3.setForeground(new java.awt.Color(255, 255, 255));
        titulo_lb3.setText("Clientes");

        subirImg_bt.setBackground(new java.awt.Color(74, 31, 61));
        subirImg_bt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        subirImg_bt.setForeground(new java.awt.Color(255, 255, 255));
        subirImg_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_refresh_25px.png"))); // NOI18N
        subirImg_bt.setText("TABLAS MODELO");
        subirImg_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirImg_btActionPerformed(evt);
            }
        });

        agregarEjercicio_bt1.setBackground(new java.awt.Color(74, 31, 61));
        agregarEjercicio_bt1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        agregarEjercicio_bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_right_25px.png"))); // NOI18N

        eliminarEjercicio_bt2.setBackground(new java.awt.Color(74, 31, 61));
        eliminarEjercicio_bt2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        eliminarEjercicio_bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_left_25px.png"))); // NOI18N

        eliminar_lb2.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        eliminar_lb2.setForeground(new java.awt.Color(255, 255, 255));
        eliminar_lb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_edit_25px_1.png"))); // NOI18N
        eliminar_lb2.setText("Modificar");
        eliminar_lb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar_lb2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminar_lb2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminar_lb2MouseExited(evt);
            }
        });

        eliminar_lb3.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        eliminar_lb3.setForeground(new java.awt.Color(255, 255, 255));
        eliminar_lb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8_plus_30px.png"))); // NOI18N
        eliminar_lb3.setText("Nueva");
        eliminar_lb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminar_lb3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminar_lb3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminar_lb3MouseExited(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cargar tablas del cliente");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Asignar  tabla  a cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(peso_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notas_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altura_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(titulo_lb)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(eliminar_lb3)
                        .addGap(34, 34, 34)
                        .addComponent(eliminar_lb)
                        .addGap(39, 39, 39)
                        .addComponent(eliminar_lb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(titulo_lb2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subirImg_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eliminarEjercicio_bt2)
                                    .addComponent(agregarEjercicio_bt1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(titulo_lb3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(eliminar_lb1)))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titulo_lb)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titulo_lb2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subirImg_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titulo_lb3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)
                        .addComponent(agregarEjercicio_bt1)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarEjercicio_bt2)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminar_lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar_lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar_lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(208, 208, 208)
                .addComponent(peso_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(altura_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notas_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String patron = patronBuscar_tf.getText();
        cargarTablaClientesBusqueda(patron);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void patronBuscar_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patronBuscar_tfKeyReleased
        String patron = patronBuscar_tf.getText();
        char teclaPulsada = evt.getKeyChar();

        if (((int) teclaPulsada) == 10) {                                     //Si es un intro (tecla 10) la tecla pulsada busca
            cargarTablaClientesBusqueda(patron);

        } else if ((((int) teclaPulsada) == 8) && (patron.length() <= 0)) {        //Si pulsa la tecla borrar y deja vacio la barra buscadora se resetea
            cargarTablaClientes();

        } else if (patron.length() >= 2) {                                    //La barra busca automaticamente a partir de los 2 caracteres
            cargarTablaClientesBusqueda(patron);

        }
    }//GEN-LAST:event_patronBuscar_tfKeyReleased

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        

        //1 Mirar si hay seleccionado un cliente en la tabla
        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada != -1) {

            //2 Obtener el dni (1 columna) del cliente seleccionado
            String dniSeleccionado = (String) jTable1.getValueAt(filaSeleccionada, 0);

            //3 Mostrar la informacion del cliente seleccionado
            mostrarDatosCliente(dniSeleccionado);

        } else {
            this.error_lbl.setText("Selecciona un trabajador primero.");
        }
        error_lbl.setText("");
    }//GEN-LAST:event_jTable1MousePressed

    private void eliminar_lbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lbMouseExited
        opcionFocusLost(evt);
    }//GEN-LAST:event_eliminar_lbMouseExited

    private void eliminar_lbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lbMouseEntered
        opcionFocusGained(evt);
    }//GEN-LAST:event_eliminar_lbMouseEntered

    private void eliminar_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lbMouseClicked
        //1 Mirar si hay seleccionado un trabajador en la tabla
        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada != -1) {

            //2 Obtener el dni (2 columna) del trabajador seleccionado
            String dniSeleccionado = (String) jTable1.getValueAt(filaSeleccionada, 0);

            //3 (en hilo) Mandar un mensaje al servidor "C7-ELIMINAR_TRABAJADOR:dni"
            eliminarCliente(dniSeleccionado);

        } else {
            this.error_lbl.setText("Selecciona un trabajador primero.");
        }

    }//GEN-LAST:event_eliminar_lbMouseClicked

    private void eliminar_lb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lb1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_lb1MouseClicked

    private void eliminar_lb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lb1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_lb1MouseEntered

    private void eliminar_lb1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lb1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_lb1MouseExited

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void subirImg_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirImg_btActionPerformed
        new Subir_Foto_interfaz(this).setVisible(true);
    }//GEN-LAST:event_subirImg_btActionPerformed

    private void eliminar_lb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lb2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_lb2MouseClicked

    private void eliminar_lb2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lb2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_lb2MouseEntered

    private void eliminar_lb2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lb2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_lb2MouseExited

    private void eliminar_lb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lb3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_lb3MouseClicked

    private void eliminar_lb3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lb3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_lb3MouseEntered

    private void eliminar_lb3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_lb3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_lb3MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEjercicio_bt1;
    private javax.swing.JLabel altura_lbl;
    private javax.swing.JButton eliminarEjercicio_bt2;
    private javax.swing.JLabel eliminar_lb;
    private javax.swing.JLabel eliminar_lb1;
    private javax.swing.JLabel eliminar_lb2;
    private javax.swing.JLabel eliminar_lb3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel notas_lbl;
    private javax.swing.JTextField patronBuscar_tf;
    private javax.swing.JLabel peso_lbl;
    private javax.swing.JButton subirImg_bt;
    private javax.swing.JLabel titulo_lb;
    private javax.swing.JLabel titulo_lb2;
    private javax.swing.JLabel titulo_lb3;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaClientes() {
        Thread thread_cargarTrabajadores = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    //1 Solicitar al servidor el listado de trabajadores (String)
                    outSocket.write("C15-LISTA_CLIENTES\n");
                    outSocket.flush();

                    String respuestaServidor = inSocket.readLine();
                    if (respuestaServidor.contains("S12-ERROR_QUERY")) {
                        System.out.println("Error al cargar la query (pendiente)");
                    } else if (respuestaServidor.contains("S20-LISTA_CLIENTES")) {
                        defaultTableMode.setRowCount(0);
                        int numeroDeUsuarios = Utilidades.contarParametros(respuestaServidor);
                        for (int i = 0; i < numeroDeUsuarios; i++) {
                            String parametroCliente = Utilidades.obtenerParametro(respuestaServidor, i + 1);
                            Object[] atributosClientes = Utilidades.obtenerCliente(parametroCliente);
                            System.out.println("fila:" + atributosClientes);
                            defaultTableMode.addRow(atributosClientes);
                        }

                    } else {
                        System.out.println("Respuesta erronea del server:" + respuestaServidor);
                    }

                } catch (IOException ex) {
                    Logger.getLogger(pnl_Rutinas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        thread_cargarTrabajadores.start();

    }

    private void eliminarCliente(String DNI) {

        Thread thread_eliminarTrabajador = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    //1. COMPROBAR si tiene FOTO, para ELIMINARLA tambien.
                    if(rutaFotoSeleccionada!=null){
                        
                        System.out.println("Interfaz: Entra en eliminar foto:"+rutaFotoSeleccionada);
                        outSocket.write("C20_ELIMINAR_FOTO:" + rutaFotoSeleccionada + "\n");
                        outSocket.flush();
                        String respuestaServidor = inSocket.readLine(); 
                        
                    }
                    
                    //2. ELIMINAR TUPLA CLIENTE desde el servidor. 

                    outSocket.write("C19_ELIMINAR_CLIENTE:" + DNI + "\n");
                    outSocket.flush();

                    String respuestaServidor = inSocket.readLine();

                    if (respuestaServidor.contains("S26-CLIENTE_NO_ENCONTRADO")) {
                        error_lbl.setText("El trabajador no ha podido ser eliminado.Otro administrador debe de haberlo eliminado o modificado.");
                    } else if (respuestaServidor.contains("S25-CLIENTE_ELIMINADO")) {
                        error_lbl.setText("Eliminacion completada exitosamente.");
                        defaultTableMode.setRowCount(0);
                        cargarTablaClientes();
                    } else {
                        error_lbl.setText("Error en el servidor. Intentelo mas tarde");
                    }

                } catch (IOException ex) {
                    Logger.getLogger(pnl_Rutinas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        thread_eliminarTrabajador.start();
    }

    private void opcionFocusGained(java.awt.event.MouseEvent evt) {
        JLabel labelFocus = (JLabel) evt.getSource();
        Font font = labelFocus.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        labelFocus.setFont(font.deriveFont(attributes));
    }

    private void opcionFocusLost(java.awt.event.MouseEvent evt) {
        JLabel labelFocus = (JLabel) evt.getSource();
        Font font = labelFocus.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        labelFocus.setFont(font.deriveFont(attributes));
    }

    private void darFormatoTabla() {

        defaultTableMode = (DefaultTableModel) this.jTable1.getModel();
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(74, 31, 61));
        jTable1.getTableHeader().setForeground(new Color(255, 255, 255));
        jTable1.getTableHeader().setPreferredSize(new Dimension(jScrollPane1.getWidth(), 50));
        jTable1.setRowHeight(50);

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(createEmptyBorder());

        Font labelFont = patronBuscar_tf.getFont();

        jTable1.getTableHeader().setFont(new Font(labelFont.getName(), Font.PLAIN, labelFont.getSize()));

        //Cambiar barra 
        jScrollPane1.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new Color(74, 31, 61);
            }

        });

        Font font = titulo_lb.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        titulo_lb.setFont(font.deriveFont(attributes));
    }

    private void cargarTablaClientesBusqueda(String patron) {
        Thread thread_cargarTrabajadores = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    //1 Solicitar al servidor el listado de trabajadores (String)
                    outSocket.write("C17-LISTAR_BUSQUEDA_CLIENTES:" + patron + "\n");
                    outSocket.flush();

                    String respuestaServidor = inSocket.readLine();
                    if (respuestaServidor.contains("S12-ERROR_QUERY")) {
                        System.out.println("Error al cargar la query (pendiente)");
                    } else if (respuestaServidor.contains("S20-LISTA_CLIENTES")) {
                        defaultTableMode.setRowCount(0);
                        int numeroDeUsuarios = Utilidades.contarParametros(respuestaServidor);  //Cuenta cuantos usuarios devuelve tras filtrar
                        for (int i = 0; i < numeroDeUsuarios; i++) {
                            String parametroCliente = Utilidades.obtenerParametro(respuestaServidor, i + 1);
                            Object[] atributosCliente = Utilidades.obtenerCliente(parametroCliente);
                            System.out.println("fila:" + atributosCliente);
                            defaultTableMode.addRow(atributosCliente);
                        }

                    } else {
                        System.out.println("Respuesta erronea del server:" + respuestaServidor);
                    }

                } catch (IOException ex) {
                    Logger.getLogger(pnl_Rutinas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        thread_cargarTrabajadores.setDaemon(true);
        thread_cargarTrabajadores.start();
    }

    private void mostrarDatosCliente(String dniSeleccionado) {
        Thread thread_mostrarCliente = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    //1 Solicitar al servidor el listado de trabajadores (String)
                    outSocket.write("C16-MOSTRAR_CLIENTE:" + dniSeleccionado + "\n");
                    outSocket.flush();

                    String respuestaServidor = inSocket.readLine();
                    if (respuestaServidor.contains("S12-ERROR_QUERY")) {
                        System.out.println("Error al cargar la query (pendiente)");
                    } else if (respuestaServidor.contains("S21-INFO_CLIENTE")) {
                        int numeroDeUsuarios = Utilidades.contarParametros(respuestaServidor);  //Cuenta cuantos usuarios devuelve tras filtrar
                        for (int i = 0; i < numeroDeUsuarios; i++) {
                            String parametroCliente = Utilidades.obtenerParametro(respuestaServidor, i + 1);
                            Object[] atributosCliente = Utilidades.obtenerDatosCliente(parametroCliente,"&");

                            dni_lbl.setText("DNI: " + atributosCliente[0]);
                            nombre_lbl.setText("Nombre:" + atributosCliente[1]);
                            apellido_lbl.setText("Apellido:" + atributosCliente[2]);
                            fecha_lbl.setText("Fecha de nacimiento::" + atributosCliente[3]);
                            peso_lbl.setText("Peso:" + atributosCliente[4]);
                            altura_lbl.setText("Altura:" + atributosCliente[5]);
                            notas_lbl.setText("Notas:" + atributosCliente[6]);

                            String rutaImagen = (String) atributosCliente[7];
                            System.out.println("Ruta cogida:"+rutaImagen);
                            if (rutaImagen.equals("") || rutaImagen==null) {
                                cargarImagenNoDisponible();
                                rutaFotoSeleccionada=null;
                            } else {
                                Utilidades.mostrarImagen(rutaImagen, imagen_lbl,200,250);
                                rutaFotoSeleccionada=rutaImagen;
                            }

                        }

                    } else {
                        System.out.println("Respuesta erronea del server:" + respuestaServidor);
                    }

                } catch (IOException ex) {
                    Logger.getLogger(pnl_Rutinas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            
            
                    
            

            

            private void cargarImagenNoDisponible() {

                try {
                    File imagenNoDisponible = new File("./src/Recursos/FotoNoDisponible.jpg");
                    byte[] imagenTotal = Files.readAllBytes(imagenNoDisponible.toPath());
                    final int ANCHURA_IMG = 200;
                    final int ALTURA_IMG = 250;
                    ByteArrayInputStream bais = new ByteArrayInputStream(imagenTotal);
                    BufferedImage img = ImageIO.read(bais);
                    System.out.println(img);
                    BufferedImage resizedImage = Utilidades.resizeImage(img, ANCHURA_IMG, ALTURA_IMG);
                    imagen_lbl.setIcon(new ImageIcon(resizedImage));

                } catch (IOException ex) {

                }

            }
        });
        thread_mostrarCliente.setDaemon(true);
        thread_mostrarCliente.start();
    }
    
    public void mostrarMensajeError(String mensaje){
        error_lbl.setText(mensaje);
    }

}
