/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles_coach;

import Paneles_Admin.*;
import Interfaces.Menu_admin_interfaz;
import Interfaces.Menu_coach_interfaz;
import Util.Utilidades;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;

/**
 *
 * @author juana
 */
public class pnl_Home_Coach extends javax.swing.JPanel {

    
    Menu_coach_interfaz interfaz_menu_padre;
    BufferedReader inSocket;
    PrintWriter outSocket;
    
    public pnl_Home_Coach(Menu_coach_interfaz interfaz_menu_padre, BufferedReader inSocket, PrintWriter outSocket) {
        
        initComponents();
        this.interfaz_menu_padre=interfaz_menu_padre;
        this.inSocket=inSocket;
        this.outSocket=outSocket;
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trabajadores_foto_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        verTrabajadores_lb = new javax.swing.JLabel();
        verTrabajadores_lb1 = new javax.swing.JLabel();
        verTrabajadores_lb2 = new javax.swing.JLabel();
        verTrabajadores_lb3 = new javax.swing.JLabel();
        trabajadores_foto_lbl1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        verTrabajadores_lb4 = new javax.swing.JLabel();
        verTrabajadores_lb5 = new javax.swing.JLabel();
        trabajadores_foto_lbl2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(186, 79, 84));

        trabajadores_foto_lbl.setForeground(new java.awt.Color(255, 255, 255));
        trabajadores_foto_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trabajadores.jpg"))); // NOI18N
        trabajadores_foto_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trabajadores_foto_lblMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLIENTES");

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bienvenido, seleccione una opcion:");

        verTrabajadores_lb.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        verTrabajadores_lb.setForeground(new java.awt.Color(255, 255, 255));
        verTrabajadores_lb.setText("Crear rutina para cliente");
        verTrabajadores_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verTrabajadores_lbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verTrabajadores_lbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verTrabajadores_lbMouseExited(evt);
            }
        });

        verTrabajadores_lb1.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        verTrabajadores_lb1.setForeground(new java.awt.Color(255, 255, 255));
        verTrabajadores_lb1.setText("Ver ficha de los clientes.");
        verTrabajadores_lb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb1MouseExited(evt);
            }
        });

        verTrabajadores_lb2.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        verTrabajadores_lb2.setForeground(new java.awt.Color(255, 255, 255));
        verTrabajadores_lb2.setText("Crear rutina para cliente");
        verTrabajadores_lb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb2MouseExited(evt);
            }
        });

        verTrabajadores_lb3.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        verTrabajadores_lb3.setForeground(new java.awt.Color(255, 255, 255));
        verTrabajadores_lb3.setText("Ver ficha de los clientes.");
        verTrabajadores_lb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb3MouseExited(evt);
            }
        });

        trabajadores_foto_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        trabajadores_foto_lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trabajadores.jpg"))); // NOI18N
        trabajadores_foto_lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trabajadores_foto_lbl1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EJERCICIOS");

        verTrabajadores_lb4.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        verTrabajadores_lb4.setForeground(new java.awt.Color(255, 255, 255));
        verTrabajadores_lb4.setText("Crear rutina para cliente");
        verTrabajadores_lb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb4MouseExited(evt);
            }
        });

        verTrabajadores_lb5.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        verTrabajadores_lb5.setForeground(new java.awt.Color(255, 255, 255));
        verTrabajadores_lb5.setText("Ver ficha de los clientes.");
        verTrabajadores_lb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verTrabajadores_lb5MouseExited(evt);
            }
        });

        trabajadores_foto_lbl2.setForeground(new java.awt.Color(255, 255, 255));
        trabajadores_foto_lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trabajadores.jpg"))); // NOI18N
        trabajadores_foto_lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trabajadores_foto_lbl2MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RUTINAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trabajadores_foto_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verTrabajadores_lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verTrabajadores_lb5)))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trabajadores_foto_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verTrabajadores_lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verTrabajadores_lb3)))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trabajadores_foto_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verTrabajadores_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verTrabajadores_lb1)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(1092, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(verTrabajadores_lb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verTrabajadores_lb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trabajadores_foto_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(verTrabajadores_lb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verTrabajadores_lb2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trabajadores_foto_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(verTrabajadores_lb5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verTrabajadores_lb4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trabajadores_foto_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void trabajadores_foto_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trabajadores_foto_lblMouseClicked
        
    }//GEN-LAST:event_trabajadores_foto_lblMouseClicked

    private void verTrabajadores_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lbMouseClicked
        //interfaz_menu_padre.cambiarPanelContenido(new pnl_Trabajadores(interfaz_menu_padre, inSocket, outSocket));
    }//GEN-LAST:event_verTrabajadores_lbMouseClicked

    private void verTrabajadores_lbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lbMouseEntered
        Utilidades.opcionFocusGained(evt);
    }//GEN-LAST:event_verTrabajadores_lbMouseEntered

    private void verTrabajadores_lbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lbMouseExited
       Utilidades.opcionFocusLost(evt);
    }//GEN-LAST:event_verTrabajadores_lbMouseExited

    private void verTrabajadores_lb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb1MouseClicked

    private void verTrabajadores_lb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb1MouseEntered

    private void verTrabajadores_lb1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb1MouseExited

    private void verTrabajadores_lb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb2MouseClicked

    private void verTrabajadores_lb2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb2MouseEntered

    private void verTrabajadores_lb2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb2MouseExited

    private void verTrabajadores_lb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb3MouseClicked

    private void verTrabajadores_lb3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb3MouseEntered

    private void verTrabajadores_lb3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb3MouseExited

    private void trabajadores_foto_lbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trabajadores_foto_lbl1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_trabajadores_foto_lbl1MouseClicked

    private void verTrabajadores_lb4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb4MouseClicked

    private void verTrabajadores_lb4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb4MouseEntered

    private void verTrabajadores_lb4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb4MouseExited

    private void verTrabajadores_lb5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb5MouseClicked

    private void verTrabajadores_lb5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb5MouseEntered

    private void verTrabajadores_lb5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTrabajadores_lb5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_verTrabajadores_lb5MouseExited

    private void trabajadores_foto_lbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trabajadores_foto_lbl2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_trabajadores_foto_lbl2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel trabajadores_foto_lbl;
    private javax.swing.JLabel trabajadores_foto_lbl1;
    private javax.swing.JLabel trabajadores_foto_lbl2;
    private javax.swing.JLabel verTrabajadores_lb;
    private javax.swing.JLabel verTrabajadores_lb1;
    private javax.swing.JLabel verTrabajadores_lb2;
    private javax.swing.JLabel verTrabajadores_lb3;
    private javax.swing.JLabel verTrabajadores_lb4;
    private javax.swing.JLabel verTrabajadores_lb5;
    // End of variables declaration//GEN-END:variables



    private void opcionFocusGained(java.awt.event.MouseEvent evt) {                                    
        JLabel labelFocus=(JLabel) evt.getSource();
        Font font= labelFocus.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        labelFocus.setFont(font.deriveFont(attributes));
    }
     
     private void opcionFocusLost(java.awt.event.MouseEvent evt) {                                  
        JLabel labelFocus=(JLabel) evt.getSource();
        Font font= labelFocus.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        labelFocus.setFont(font.deriveFont(attributes));
    }



}


